### ISSUE TITLE
Hyperlink to researcher's profile

### ISSUE THREAD

**Issue by amriteya** [aditpandey3090/Tree-Visualization-Survey#12]
<img width="555" alt="Tree_Visualization_Survey" src="https://user-images.githubusercontent.com/4987564/82124451-bce6fd80-9764-11ea-818a-747dc68fd0a2.png">

Researchers card doesn't have a hyperlink to their profile.

@aditpandey3090 Should that be added?

**Comment by aditpandey3090** [comment]
Change the name of Michelle to Michelle A. Borkin
